[pytest]

testpath = tests

markers =
    smoke: Critical smoke test
    regression: Full regression tests
    ui: UI tests
    api: API tests
    integeration: End-to-End integeration tests

adopts=
    -v
    --tracing=retain-on-failure
    --screenshot=only-on-failure
    ---video=retain-on-failure
    